// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynjwrrovhhecefgminvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inluandycm92aGhlY2VmZ21pbnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjA4MDksImV4cCI6MjA2MTQ5NjgwOX0.Bt4oYTu014tSrkpsRsHtZDRHa2zCIhlumKkpdMPiO2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);